### ISSUE TITLE
타이틀 텍스트 화면 개선

### ISSUE THREAD

**Issue by jsontype** [jsontype/movieapp#7]
왼쪽 패딩 20px
상하 가운데정렬
폰트 h1태그로 고쳐서 크게

**Comment by mildmint1** [comment]
@jsontype 왼쪽 패딩 20px , 상하는 가운데정렬 완료 하였습니다.
폰트는 h1 태그로 크게 수정하는 법을 몰라서 font-size: 30px으로 수정하였습니다.
